Phonebook/Models/HandbookRecord.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Phonebook.Models
{
    public class HandbookRecord
    {
        [Required]
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(20)]
        [RegularExpression("[A-z]{2,}")]
        public string LastName { get; set; }
        [Required]
        [Index(IsUnique = true)]
        [StringLength(20)]
        [Phone]
        public string Phone { get; set; }
    }
}

Phonebook/Models/IRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Phonebook.Models
{
    public interface IRepository<T> where T : class
    {
        IEnumerable<T> GetRecords(); // получение всех объектов
        T GetRecord(int id); // получение одного объекта по id
        void Create(T item); // создание объекта
        void Update(T item); // обновление объекта
        void Delete(int id); // удаление объекта по id
    }
}

Phonebook/Models/JsonRepository.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;

namespace Phonebook.Models
{
    public class JsonRepository : IRepository<HandbookRecord>
    {
        readonly string jsonFilePath = @"D:/Labs/ASP/Phonebook/Phonebook/App_Data/database.json";
        public void Create(HandbookRecord item)
        {
            var jsonData = File.ReadAllText(jsonFilePath);
            var handbookRecordList = JsonConvert.DeserializeObject<List<HandbookRecord>>(jsonData) ?? new List<HandbookRecord>();
            if(handbookRecordList.Count != 0)
            {
                item.Id = handbookRecordList.Max(x => x.Id) + 1;
            }
            bool recordAlreadyExists = handbookRecordList.Exists(x => x.LastName == item.LastName && x.Phone == item.Phone);
            if (!recordAlreadyExists)
            {
                handbookRecordList.Add(item);
                jsonData = JsonConvert.SerializeObject(handbookRecordList);
                File.WriteAllText(jsonFilePath, jsonData);
            }
        }

        public void Delete(int id)
        {
            var jsonData = File.ReadAllText(jsonFilePath);
            var handbookRecordList = JsonConvert.DeserializeObject<List<HandbookRecord>>(jsonData) ?? new List<HandbookRecord>();
            var handbookRecord = handbookRecordList.Where(x => x.Id == id).FirstOrDefault();
            if (handbookRecord != null)
            {
                handbookRecordList.Remove(handbookRecord);
                jsonData = JsonConvert.SerializeObject(handbookRecordList);
                File.WriteAllText(jsonFilePath, jsonData);
            }
        }

        public HandbookRecord GetRecord(int id)
        {
            var jsonData = File.ReadAllText(jsonFilePath);
            var handbookRecordList = JsonConvert.DeserializeObject<List<HandbookRecord>>(jsonData) ?? new List<HandbookRecord>();
            HandbookRecord handbookRecord = handbookRecordList.Where(x => x.Id == id).FirstOrDefault();
            return handbookRecord;
        }

        public IEnumerable<HandbookRecord> GetRecords()
        {
            var jsonData = File.ReadAllText(jsonFilePath);
            var handbookRecordList = JsonConvert.DeserializeObject<List<HandbookRecord>>(jsonData) ?? new List<HandbookRecord>();
            var sortedList = handbookRecordList.OrderBy(x => x.LastName).ToList();
            return sortedList;
        }

        public void Update(HandbookRecord item)
        {
            var jsonData = File.ReadAllText(jsonFilePath);
            var handbookRecordList = JsonConvert.DeserializeObject<List<HandbookRecord>>(jsonData) ?? new List<HandbookRecord>();
            var obj = handbookRecordList.Where(x => x.Id == item.Id).FirstOrDefault();
            if (obj != null)
            {
                if(obj.LastName == item.LastName)
                {
                    if (obj.Phone != item.Phone)
                    {
                        bool numberAlreadyExists = handbookRecordList.Count(x => x.Phone == item.Phone) == 1;
                        if (!numberAlreadyExists)
                        {
                            obj.Phone = item.Phone;
                            jsonData = JsonConvert.SerializeObject(handbookRecordList);
                            File.WriteAllText(jsonFilePath, jsonData);
                        }
                    }
                }
                else
                {
                    obj.LastName = item.LastName;
                    if(obj.Phone != item.Phone)
                    {
                        bool numberAlreadyExists = handbookRecordList.Count(x => x.Phone == item.Phone) == 1;
                        if (!numberAlreadyExists)
                        {
                            obj.Phone = item.Phone;
                        }
                    }
                    jsonData = JsonConvert.SerializeObject(handbookRecordList);
                    File.WriteAllText(jsonFilePath, jsonData);
                }
            }
        }
    }
}

Phonebook/Controllers/DictController.cs
using Phonebook.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Phonebook.Controllers
{
    public class DictController : Controller
    {
        readonly IRepository<HandbookRecord> _handbookRecordRepository;
        // GET: Dict
        public DictController(IRepository<HandbookRecord> repository)
        {
            _handbookRecordRepository = repository;
        }
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.getall = _handbookRecordRepository.GetRecords();
            return View();
        }
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddSave(string LastName, string Phone)
        {
            HandbookRecord handbookRecord = new HandbookRecord
            {
                Id = 0,
                LastName = LastName, 
                Phone = Phone 
            };
            _handbookRecordRepository.Create(handbookRecord);
            try
            {
                _handbookRecordRepository.Save();
            }
            catch(Exception ex)
            {
                return Redirect("/Dict/Add");
            }
            return Redirect("/Dict/Index");
        }
        [HttpGet]
        public ActionResult Update(int id) 
        {
            var handbookRecord = _handbookRecordRepository.GetRecord(id);
            if(handbookRecord != null) 
            {
                ViewBag.handbookRecord = handbookRecord;
                return View();
            }
            else
            {
                return Redirect("/Dict/Index");
            }
        }
        [HttpPost]
        public ActionResult UpdateSave(string LastName, string Phone,int Id)
        {
            HandbookRecord handbookRecord = new HandbookRecord
            {
                Id = Id,
                LastName = LastName,
                Phone = Phone
            };
            _handbookRecordRepository.Update(handbookRecord);
            try
            {
                _handbookRecordRepository.Save();
            }
            catch(Exception ex)
            {
                return Redirect("/Dict/Index");
            }
            return Redirect("/Dict/Index");
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var handbookRecord = _handbookRecordRepository.GetRecord(id);
            if (handbookRecord != null)
            {
                ViewBag.Id = handbookRecord.Id;
                return View();
            }
            else
            {
                return Redirect("/Dict/Index");
            }
        }
        [HttpPost]
        public ActionResult DeleteSave(int id) 
        { 
            _handbookRecordRepository.Delete(id);
            _handbookRecordRepository.Save();
            return Redirect("/Dict/Index");
        }
    }
}

Phonebook/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Phonebook.Controllers
{
    public class ErrorController : Controller
    {
        // GET: Error
        public ActionResult Error()
        {
            Response.StatusCode = 404;

            ViewBag.url = Request.Url.ToString().Split(';')[1];
            ViewBag.method = Request.HttpMethod;
            return View();
        }
    }
}

Phonebook/Views/Dict/Add.cshtml
@model Phonebook.Models.HandbookRecord
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add</title>
</head>
<p><a href="/Dict/Index">Главная страница</a></p>
<body>
    @*@using (Html.BeginForm("AddSave", "Dict", FormMethod.Post))
        {
                <table>
                    <tr>
                        <td>Введите фамилию: </td>
                        <td>
                            @Html.TextBoxFor(m => m.LastName)
                        </td>
                    </tr>
                    <tr>
                        <td>Введите номер телефона: </td>
                        <td>
                            @Html.TextBoxFor(m => m.Phone)
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><input type="submit" value="Submit" /></td>
                    </tr>
                </table>
        }*@
    <form method="post" action="/Dict/AddSave">
        <table>
            <tr>
                <td><p>Введите фамилию: </p></td>
                <td><input type="text" name="LastName"/> </td>
            </tr>
            <tr>
                <td><p>Введите номер телефона: </p></td>
                <td><input type="text" name="Phone"/> </td>
            </tr>
            <tr>
                <td><input type="submit" value="Отправить" /> </td>
                <td></td>
            </tr>
        </table>
    </form>
</body>
</html>

Phonebook/Views/Dict/Delete.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <form method="post" action="/Dict/DeleteSave">
        <input type="hidden" name="Id" value="@ViewBag.Id" />
        <table>
            <tr>
                <td><input type="submit" value="Удалить запись с Id = @ViewBag.Id" /> </td>
                <td></td>
            </tr>
        </table>
    </form>
</body>
</html>

Phonebook/Views/Dict/Index.cshtml
@{
    Layout = null;
    List<Phonebook.Models.HandbookRecord> handbookRecords = ViewBag.getall;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>MVC_3</title>
</head>
<body>
    <div>
        <h3>Телефонный справочник</h3>
        <p><a href="/Dict/Add">Добавить запись</a></p>
        <table border="1">
            <tr>
                <td><p>ID</p></td>
                <td><p>Фамилия</p></td>
                <td><p>Номер</p></td>
                <td><p>Действия</p></td>
            </tr>
            @foreach (var b in handbookRecords)
            {
                <tr>
                    <td><p>@b.Id</p></td>
                    <td><p>@b.LastName</p></td>
                    <td><p>@b.Phone</p></td>
                    <td>
                        <p><a href="/Dict/Update/?id=@b.Id">Изменить</a></p>
                        <p><a href="/Dict/Delete/?id=@b.Id">Удалить</a></p>
                    </td>
                </tr>
            }
        </table>
    </div>
</body>
</html>

Phonebook/Views/Dict/Update.cshtml
@model Phonebook.Models.HandbookRecord
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Update</title>
</head>
<p><a href="/Dict/Index">Главная страница</a></p>
<body>
    @*@using (Html.BeginForm("UpdateSave", "Dict", FormMethod.Post))
        {
            <table>
                <tr>
                    <td>Введите фамилию: </td>
                    <td>
                        @Html.TextBoxFor(m => m.LastName, new {@Value = ViewBag.handbookRecord.LastName})
                    </td>
                </tr>
                <tr>
                    <td>Введите номер телефона: </td>
                    <td>
                        @Html.TextBoxFor(m => m.Phone, new { @Value = ViewBag.handbookRecord.Phone })
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" value="Submit" /></td>
                </tr>
            </table>
        }*@
    <form method="post" action="/Dict/UpdateSave">
        <input type="hidden" name="Id" value="@ViewBag.handbookRecord.Id" />
        <table>
            <tr>
                <td><p>Введите фамилию: </p></td>
                <td><input type="text" name="LastName" value=@ViewBag.handbookRecord.LastName /> </td>
            </tr>
            <tr>
                <td><p>Введите номер телефона: </p></td>
                <td><input type="text" name="Phone" value=@ViewBag.handbookRecord.Phone /> </td>
            </tr>
            <tr>
                <td><input type="submit" value="Отправить" /> </td>
                <td></td>
            </tr>
        </table>
    </form>
</body>
</html>

Phonebook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="Дополнительные параметры">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Имя приложения", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                    <li>@Html.ActionLink("Информация", "About", "Home")</li>
                    <li>@Html.ActionLink("Связаться", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - мое приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>